merge into FILM_GENRE (GENRE_ID, GENRE)
    values ( 1, 'Комедия' );
merge into FILM_GENRE (GENRE_ID, GENRE)
    values ( 2, 'Драма' );
merge into FILM_GENRE (GENRE_ID, GENRE)
    values ( 3, 'Мультфильм' );
merge into FILM_GENRE (GENRE_ID, GENRE)
    values ( 4, 'Триллер' );
merge into FILM_GENRE (GENRE_ID, GENRE)
    values ( 5, 'Документальный' );
merge into FILM_GENRE (GENRE_ID, GENRE)
    values ( 6, 'Боевик' );
merge into RATING_MPA (RATING_ID, RATING)
    values ( 1, 'G' );
merge into RATING_MPA (RATING_ID, RATING)
    values ( 2, 'PG' );
merge into RATING_MPA (RATING_ID, RATING)
    values ( 3, 'PG-13' );
merge into RATING_MPA (RATING_ID, RATING)
    values ( 4, 'R' );
merge into RATING_MPA (RATING_ID, RATING)
    values ( 5, 'NC-17' );